server:
  port: 8900

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    jackson:
      date-format: yyyy:MM:dd HH:mm:ss
      time-zone: GMT+8
    http:
      multipart:
        max-file-size: 100Mb
        max-request-size: 100Mb

swagger:
  title: ${spring.application.name} API
  description: ${spring.application.name} API
  creator: ${spring.application.name}
  version: 1.0.0
  ##只能扫描实现类所在包
  basepackage: com.bksuns.zzdljc

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml